name: ZooPR
version: '${project.version}'
main: me.sildev.zoopr.ZooPR
api-version: 1.19
authors: [ siloonk ]
description: ZooPR Core

commands:
  bal:
    description: bal command!

  pay:
    description: pay command!

  vanish:
    description: vanish command!

  ban:
    description: ban command!

  rankup:
    aliases: [ ru ]
    description: rankup command!

  prestige:
    description: prestige command!

  gang:
    description: gang command!

  prestigemax:
    description: prestigemax command!

  robot:
    description: robot command!

  pvespawner:
    description: pvespawner command!

  bomb:
    description: bomb command!

  baltop:
    description: baltop command!

  beacontop:
    description: beacontop command!

  tokentop:
    description: tokentop command!

  pouch:
    description: pouch command!

  booster:
    description: booster command!

  ce:
    description: ce command!

  rebirth:
    description: rebirth command!

  pet:
    description: pet command!

  quest:
    description: quest command!